version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/react-app"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
